hydra:
  output_subdir: null

save_model_path: model_weights/model_weights.pt

dataset:
  root: ../data # for GCP - use "data/""
  dataset: Flowers102 # Flowers102 or FashionMNIST

train:
  epochs: 2
  lr: 3e-4
  weight_decay: 5e-5

show_model_summary: False
num_classes : 102

vit-base:
  img_dim: (3, 224, 224)
  patch_size: 16
  num_classes: ${num_classes}
  hidden_dim: 768
  num_heads: 12
  num_transformers: 12

vit-large:
  img_dim: (3, 224, 224)
  patch_size: 16
  num_classes: ${num_classes}
  hidden_dim: 1024
  num_heads: 16
  num_transformers: 24

vit-huge:
  img_dim: (3, 224, 224)
  patch_size: 16
  num_classes: ${num_classes}
  hidden_dim: 1280
  num_heads: 16
  num_transformers: 32